spring:
  application:
    name: friendexam

  datasource:
    url: jdbc:mysql://localhost:3306/Example
    username: mhje11
    password: 9704
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8080
